app:
  name: "aptiverse-email-service"
  max_workers: 5
  log_level: "info"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue_name: "email_queue"

smtp:
  host: "smtp.gmail.com"
  port: "587"
  username: "your-email@gmail.com"
  from: "your-email@gmail.com"

retry:
  max_attempts: 3
  backoff_multiplier: 2
  initial_interval: "1s"